-- Teil 1: Tabellendesign

CREATE TABLE bundesliga_tipps
	( 
	spiel_id	Number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
	spieltag	Number NOT NULL CONSTRAINT chk_spieltag_moeglich check(spieltag BETWEEN 1 AND 34),
	heim_team	varchar2(20),
	gast_team	varchar2(20),
	tipp		varchar2(5),
	ergebnis	varchar2(5)
	);

COMMIT;

