-- Teil 1: Tabellendesign

CREATE TABLE bundesliga_tipps
	( 
	spiel_id	Number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
	spieltag	Number NOT NULL CONSTRAINT chk_spieltag_moeglich check(spieltag BETWEEN 1 AND 34),
	heim_team	varchar2(20),
	gast_team	varchar2(20),
	tipp		varchar2(5),
	ergebnis	varchar2(5)
	);

COMMIT;

-- ==========================================
-- DYNAMISCHES DASHBOARD: PUNKTE & STATISTIK
-- ==========================================
CREATE OR REPLACE VIEW v_tippspiel_tabelle AS
	SELECT   spieltag, 
	         SUM(punkte) AS gewonnene_punkte,
	         COUNT(CASE WHEN punkte = 4 THEN 1 END) AS exakte_tipps,
	         COUNT(CASE WHEN punkte = 3 THEN 1 END) AS tordifferenz_treffer,
	         COUNT(CASE WHEN punkte = 2 THEN 1 END) AS tendenz_treffer
	FROM     bundesliga_tipps
	GROUP BY spieltag
	ORDER BY gewonnene_punkte DESC;
